pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "This is building stage"
                sh './gradlew build'
            }
        }
        stage('Test') {
            parallel {
                stage("Unit Test") {
                    steps {
                        echo "This is testing stage"
                        sh './gradlew unitTest'
                    }
                }
                stage("Integration Test") {
                    steps {
                        echo "This is testing stage"
                        sh './gradlew integrationTest'
                    }
                }

            }
        }
        stage('Deploy') {
            steps {
                echo "This is deploy Stage"
            }
        }
    }
}