pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "This is building stage"
            }
        }
        stage('Test') {
            steps {
                echo "This is testing stage"
            }
        }
        stage('Deploy') {
            steps {
                echo "This is deploy Stage"
            }
        }
    }
}